#!/usr/bin/env python3
"""
Daily regime-switching research watchdog.

Fires every morning at 07:00 IST via LaunchAgent. Each run:
  1. Picks today's topic from the rotation (deterministic by date)
  2. Writes a starter file at docs/research/regime-switching-daily/YYYY-MM-DD.md
     pre-populated with the topic, prior-cycle reference (if any), and the
     research-agent prompt to paste into Claude
  3. Sends a Telegram with the topic and starter-file path
  4. Optionally invokes Claude (requires CLAUDE_CLI=true env, default off —
     by default Soumya runs the research himself when he opens a session)

Path note: this file lives in ~/Library/Application Support/tradepilot/
because launchd's TCC sandbox blocks reading scripts inside ~/Documents.
The script accesses ~/Documents at runtime, which is fine.
"""
from __future__ import annotations

import os
import sys
import urllib.parse
import urllib.request
from datetime import date, datetime
from pathlib import Path

PROJECT = Path("/Users/soumyaswain/Documents/tinker/projects/tradepilot")
DAILY_DIR = PROJECT / "docs" / "research" / "regime-switching-daily"
TOPICS_FILE = DAILY_DIR / "_topics.md"

# Topic rotation — keep in sync with _topics.md table
TOPICS = [
    "Recent arxiv papers (last 30 days) on regime-switching trading",
    "hmmlearn vs pomegranate vs hmmkit Python libraries",
    "Bayesian Online Change-Point Detection (BOCPD) — implementations + tuning",
    "Indian VIX (India VIX) regime behaviour — recent studies",
    "Bull/bear regime persistence in NSE — empirical studies 2020-2026",
    "FII/DII as regime leading indicator — recent papers",
    "Walk-forward Combinatorial Purged CV (CPCV) — open-source implementations",
    "Look-ahead bias detection tools in time-series ML",
    "Kaufman Efficiency Ratio — intraday regime confirm",
    "Bank-Nifty/Nifty ratio as regime tell — Indian-specific",
    "Sector rotation as regime signal — Indian sectors",
    "Options skew / PCR as regime indicator",
    "Multi-resolution regime detection (daily + intraday)",
    "Renaissance Medallion 2025-2026 disclosures",
    "Two Sigma machine learning regime modeling updates",
    "AQR factor timing — newest publications",
    "Indian quant fund disclosures (True Beacon, Dolat, Quant MF)",
    "F&O expiry day regime effects — recent research",
    "Budget day Indian market behaviour — historical",
    "RBI policy day market reaction patterns",
    "Indian election cycle regime data",
    "Order flow imbalance as regime indicator",
    "Volume profile regime classification",
    "Statistical jump models (Nystrup et al 2024 follow-ups)",
    "Probability of Backtest Overfitting (PBO) — implementations",
    "Deflated Sharpe Ratio — references + libraries",
    "LightGBM regime-aware tutorials + GitHub repos",
    "Hidden Markov Model online refit strategies",
    "Soft-mixture vs hard-switch routing — empirical comparisons",
    "Position handoff patterns in multi-strategy funds",
]


def pick_topic_for(d: date) -> tuple[int, str]:
    idx = d.toordinal() % len(TOPICS)
    return idx, TOPICS[idx]


def find_prior_coverage(idx: int, today: date) -> Path | None:
    """Find the most recent file that covered the same topic index."""
    if not DAILY_DIR.exists():
        return None
    candidates = sorted(DAILY_DIR.glob("20*-*-*.md"), reverse=True)
    for fp in candidates:
        try:
            d = datetime.strptime(fp.stem, "%Y-%m-%d").date()
        except ValueError:
            continue
        if d >= today:
            continue
        if d.toordinal() % len(TOPICS) == idx:
            return fp
    return None


def write_starter_file(today: date, idx: int, topic: str, prior: Path | None) -> Path:
    out = DAILY_DIR / f"{today.isoformat()}.md"
    if out.exists():
        return out  # idempotent — don't overwrite an existing day's research

    prior_section = ""
    if prior is not None:
        prior_section = (
            f"\n## Prior coverage of this topic\n\n"
            f"The same topic (#{idx + 1}) was last researched on {prior.stem}. "
            f"See `{prior.relative_to(PROJECT)}` for prior findings. **Compare and "
            f"note what's NEW** in today's research — focus on changes since.\n"
        )

    content = f"""# Daily Regime-Switching Research — {today.isoformat()}

**Topic #{idx + 1} of {len(TOPICS)}**: {topic}

> Auto-generated by `scripts/regime-switching-daily-research.py` at
> {datetime.now().strftime('%H:%M:%S IST')}. Soumya: when you open a Claude
> session today, paste the prompt block below to fill in this file.

---

## Research-agent prompt (paste into Claude)

```
Research today's regime-switching daily topic for TradePilot. Working directory: /Users/soumyaswain/Documents/tinker/projects/tradepilot.

TODAY'S TOPIC (#{idx + 1} of {len(TOPICS)}): {topic}

YOUR JOB:
1. Spend 5-10 minutes searching the web for the latest information on this topic. Prefer:
   - arxiv.org for academic papers (filter by last 30 days where possible)
   - GitHub for libraries and implementations
   - Bloomberg / FT / Risk.net / livemint / capitalmind for industry perspective
   - Official broker / SEBI / NSE / RBI sources for Indian-specific data
2. Update docs/research/regime-switching-daily/{today.isoformat()}.md with the structure below. KEEP THE EXISTING TOPIC LINE AND PRIOR-COVERAGE LINK if present.
3. Append findings under "## Key findings" — bullet points, citations inline.
4. Append sources under "## Sources".
5. If prior coverage exists, append "## Comparison notes — what's new since prior coverage".
6. When done, send a Telegram via .env TELEGRAM_BOT_TOKEN/TELEGRAM_CHAT_ID with one-line summary.

CONSTRAINTS:
- Maximum runtime: 12 minutes total
- Use Bash timeout: 720000 on long commands
- WebSearch + WebFetch limit: 8 calls total
- Do NOT use sleep-poll loops
- Do NOT spawn sub-agents
```
{prior_section}
---

## Key findings

(To be filled by the research agent.)

---

## Sources

(To be filled by the research agent.)

---

## Comparison notes — what's new since prior coverage

(Only filled if prior coverage exists. Otherwise leave blank.)
"""
    out.write_text(content)
    return out


def telegram(msg: str) -> None:
    env = PROJECT / ".env"
    if not env.exists():
        return
    token = chat = None
    for line in env.read_text().splitlines():
        if line.startswith("TELEGRAM_BOT_TOKEN="):
            token = line.split("=", 1)[1].strip().strip('"')
        elif line.startswith("TELEGRAM_CHAT_ID="):
            chat = line.split("=", 1)[1].strip().strip('"')
    if not (token and chat):
        return
    try:
        data = urllib.parse.urlencode({"chat_id": chat, "text": msg}).encode()
        urllib.request.urlopen(
            f"https://api.telegram.org/bot{token}/sendMessage",
            data=data, timeout=8,
        )
    except Exception as e:
        print(f"warn: telegram failed: {e}", file=sys.stderr)


def main() -> int:
    today = date.today()
    idx, topic = pick_topic_for(today)
    prior = find_prior_coverage(idx, today)
    out = write_starter_file(today, idx, topic, prior)

    msg_lines = [
        f"🔬 Daily regime-switching research topic #{idx + 1}:",
        topic,
        "",
        f"Starter file: docs/research/regime-switching-daily/{today.isoformat()}.md",
    ]
    if prior is not None:
        msg_lines.append(f"Prior coverage: {prior.stem}")
    msg_lines.append("")
    msg_lines.append(
        "Open Claude when convenient and paste the prompt block in the file."
    )
    telegram("\n".join(msg_lines))

    print(f"[regime-research] wrote {out}")
    print(f"[regime-research] topic #{idx + 1}: {topic}")
    if prior:
        print(f"[regime-research] prior coverage at {prior}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
